// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package xcallback

import (
	"context"
	"sync"
)

// Ensure, that XCallbackMock does implement XCallback.
// If this is not the case, regenerate this file with moq.
var _ XCallback = &XCallbackMock{}

// XCallbackMock is a mock implementation of XCallback.
//
//	func TestSomethingThatUsesXCallback(t *testing.T) {
//
//		// make and configure a mocked XCallback
//		mockedXCallback := &XCallbackMock{
//			AddFileFunc: func(ctx context.Context, token string, bearID string, filename string, fileData []byte) error {
//				panic("mock out the AddFile method")
//			},
//			AddTagFunc: func(ctx context.Context, token string, bearID string, tag string) error {
//				panic("mock out the AddTag method")
//			},
//			ArchiveFunc: func(ctx context.Context, token string, bearID string) error {
//				panic("mock out the Archive method")
//			},
//			CreateFunc: func(ctx context.Context, token string, title string, body string, tags []string) (string, error) {
//				panic("mock out the Create method")
//			},
//			DeleteTagFunc: func(ctx context.Context, token string, tagName string) error {
//				panic("mock out the DeleteTag method")
//			},
//			RenameTagFunc: func(ctx context.Context, token string, oldName string, newName string) error {
//				panic("mock out the RenameTag method")
//			},
//			TrashFunc: func(ctx context.Context, token string, bearID string) error {
//				panic("mock out the Trash method")
//			},
//			UpdateFunc: func(ctx context.Context, token string, bearID string, body string) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedXCallback in code that requires XCallback
//		// and then make assertions.
//
//	}
type XCallbackMock struct {
	// AddFileFunc mocks the AddFile method.
	AddFileFunc func(ctx context.Context, token string, bearID string, filename string, fileData []byte) error

	// AddTagFunc mocks the AddTag method.
	AddTagFunc func(ctx context.Context, token string, bearID string, tag string) error

	// ArchiveFunc mocks the Archive method.
	ArchiveFunc func(ctx context.Context, token string, bearID string) error

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, token string, title string, body string, tags []string) (string, error)

	// DeleteTagFunc mocks the DeleteTag method.
	DeleteTagFunc func(ctx context.Context, token string, tagName string) error

	// RenameTagFunc mocks the RenameTag method.
	RenameTagFunc func(ctx context.Context, token string, oldName string, newName string) error

	// TrashFunc mocks the Trash method.
	TrashFunc func(ctx context.Context, token string, bearID string) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, token string, bearID string, body string) error

	// calls tracks calls to the methods.
	calls struct {
		// AddFile holds details about calls to the AddFile method.
		AddFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// BearID is the bearID argument value.
			BearID string
			// Filename is the filename argument value.
			Filename string
			// FileData is the fileData argument value.
			FileData []byte
		}
		// AddTag holds details about calls to the AddTag method.
		AddTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// BearID is the bearID argument value.
			BearID string
			// Tag is the tag argument value.
			Tag string
		}
		// Archive holds details about calls to the Archive method.
		Archive []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// BearID is the bearID argument value.
			BearID string
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// Title is the title argument value.
			Title string
			// Body is the body argument value.
			Body string
			// Tags is the tags argument value.
			Tags []string
		}
		// DeleteTag holds details about calls to the DeleteTag method.
		DeleteTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// TagName is the tagName argument value.
			TagName string
		}
		// RenameTag holds details about calls to the RenameTag method.
		RenameTag []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// OldName is the oldName argument value.
			OldName string
			// NewName is the newName argument value.
			NewName string
		}
		// Trash holds details about calls to the Trash method.
		Trash []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// BearID is the bearID argument value.
			BearID string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// BearID is the bearID argument value.
			BearID string
			// Body is the body argument value.
			Body string
		}
	}
	lockAddFile   sync.RWMutex
	lockAddTag    sync.RWMutex
	lockArchive   sync.RWMutex
	lockCreate    sync.RWMutex
	lockDeleteTag sync.RWMutex
	lockRenameTag sync.RWMutex
	lockTrash     sync.RWMutex
	lockUpdate    sync.RWMutex
}

// AddFile calls AddFileFunc.
func (mock *XCallbackMock) AddFile(ctx context.Context, token string, bearID string, filename string, fileData []byte) error {
	if mock.AddFileFunc == nil {
		panic("XCallbackMock.AddFileFunc: method is nil but XCallback.AddFile was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Token    string
		BearID   string
		Filename string
		FileData []byte
	}{
		Ctx:      ctx,
		Token:    token,
		BearID:   bearID,
		Filename: filename,
		FileData: fileData,
	}
	mock.lockAddFile.Lock()
	mock.calls.AddFile = append(mock.calls.AddFile, callInfo)
	mock.lockAddFile.Unlock()
	return mock.AddFileFunc(ctx, token, bearID, filename, fileData)
}

// AddFileCalls gets all the calls that were made to AddFile.
// Check the length with:
//
//	len(mockedXCallback.AddFileCalls())
func (mock *XCallbackMock) AddFileCalls() []struct {
	Ctx      context.Context
	Token    string
	BearID   string
	Filename string
	FileData []byte
} {
	var calls []struct {
		Ctx      context.Context
		Token    string
		BearID   string
		Filename string
		FileData []byte
	}
	mock.lockAddFile.RLock()
	calls = mock.calls.AddFile
	mock.lockAddFile.RUnlock()
	return calls
}

// AddTag calls AddTagFunc.
func (mock *XCallbackMock) AddTag(ctx context.Context, token string, bearID string, tag string) error {
	if mock.AddTagFunc == nil {
		panic("XCallbackMock.AddTagFunc: method is nil but XCallback.AddTag was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Token  string
		BearID string
		Tag    string
	}{
		Ctx:    ctx,
		Token:  token,
		BearID: bearID,
		Tag:    tag,
	}
	mock.lockAddTag.Lock()
	mock.calls.AddTag = append(mock.calls.AddTag, callInfo)
	mock.lockAddTag.Unlock()
	return mock.AddTagFunc(ctx, token, bearID, tag)
}

// AddTagCalls gets all the calls that were made to AddTag.
// Check the length with:
//
//	len(mockedXCallback.AddTagCalls())
func (mock *XCallbackMock) AddTagCalls() []struct {
	Ctx    context.Context
	Token  string
	BearID string
	Tag    string
} {
	var calls []struct {
		Ctx    context.Context
		Token  string
		BearID string
		Tag    string
	}
	mock.lockAddTag.RLock()
	calls = mock.calls.AddTag
	mock.lockAddTag.RUnlock()
	return calls
}

// Archive calls ArchiveFunc.
func (mock *XCallbackMock) Archive(ctx context.Context, token string, bearID string) error {
	if mock.ArchiveFunc == nil {
		panic("XCallbackMock.ArchiveFunc: method is nil but XCallback.Archive was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Token  string
		BearID string
	}{
		Ctx:    ctx,
		Token:  token,
		BearID: bearID,
	}
	mock.lockArchive.Lock()
	mock.calls.Archive = append(mock.calls.Archive, callInfo)
	mock.lockArchive.Unlock()
	return mock.ArchiveFunc(ctx, token, bearID)
}

// ArchiveCalls gets all the calls that were made to Archive.
// Check the length with:
//
//	len(mockedXCallback.ArchiveCalls())
func (mock *XCallbackMock) ArchiveCalls() []struct {
	Ctx    context.Context
	Token  string
	BearID string
} {
	var calls []struct {
		Ctx    context.Context
		Token  string
		BearID string
	}
	mock.lockArchive.RLock()
	calls = mock.calls.Archive
	mock.lockArchive.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *XCallbackMock) Create(ctx context.Context, token string, title string, body string, tags []string) (string, error) {
	if mock.CreateFunc == nil {
		panic("XCallbackMock.CreateFunc: method is nil but XCallback.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
		Title string
		Body  string
		Tags  []string
	}{
		Ctx:   ctx,
		Token: token,
		Title: title,
		Body:  body,
		Tags:  tags,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, token, title, body, tags)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedXCallback.CreateCalls())
func (mock *XCallbackMock) CreateCalls() []struct {
	Ctx   context.Context
	Token string
	Title string
	Body  string
	Tags  []string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
		Title string
		Body  string
		Tags  []string
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteTag calls DeleteTagFunc.
func (mock *XCallbackMock) DeleteTag(ctx context.Context, token string, tagName string) error {
	if mock.DeleteTagFunc == nil {
		panic("XCallbackMock.DeleteTagFunc: method is nil but XCallback.DeleteTag was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Token   string
		TagName string
	}{
		Ctx:     ctx,
		Token:   token,
		TagName: tagName,
	}
	mock.lockDeleteTag.Lock()
	mock.calls.DeleteTag = append(mock.calls.DeleteTag, callInfo)
	mock.lockDeleteTag.Unlock()
	return mock.DeleteTagFunc(ctx, token, tagName)
}

// DeleteTagCalls gets all the calls that were made to DeleteTag.
// Check the length with:
//
//	len(mockedXCallback.DeleteTagCalls())
func (mock *XCallbackMock) DeleteTagCalls() []struct {
	Ctx     context.Context
	Token   string
	TagName string
} {
	var calls []struct {
		Ctx     context.Context
		Token   string
		TagName string
	}
	mock.lockDeleteTag.RLock()
	calls = mock.calls.DeleteTag
	mock.lockDeleteTag.RUnlock()
	return calls
}

// RenameTag calls RenameTagFunc.
func (mock *XCallbackMock) RenameTag(ctx context.Context, token string, oldName string, newName string) error {
	if mock.RenameTagFunc == nil {
		panic("XCallbackMock.RenameTagFunc: method is nil but XCallback.RenameTag was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Token   string
		OldName string
		NewName string
	}{
		Ctx:     ctx,
		Token:   token,
		OldName: oldName,
		NewName: newName,
	}
	mock.lockRenameTag.Lock()
	mock.calls.RenameTag = append(mock.calls.RenameTag, callInfo)
	mock.lockRenameTag.Unlock()
	return mock.RenameTagFunc(ctx, token, oldName, newName)
}

// RenameTagCalls gets all the calls that were made to RenameTag.
// Check the length with:
//
//	len(mockedXCallback.RenameTagCalls())
func (mock *XCallbackMock) RenameTagCalls() []struct {
	Ctx     context.Context
	Token   string
	OldName string
	NewName string
} {
	var calls []struct {
		Ctx     context.Context
		Token   string
		OldName string
		NewName string
	}
	mock.lockRenameTag.RLock()
	calls = mock.calls.RenameTag
	mock.lockRenameTag.RUnlock()
	return calls
}

// Trash calls TrashFunc.
func (mock *XCallbackMock) Trash(ctx context.Context, token string, bearID string) error {
	if mock.TrashFunc == nil {
		panic("XCallbackMock.TrashFunc: method is nil but XCallback.Trash was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Token  string
		BearID string
	}{
		Ctx:    ctx,
		Token:  token,
		BearID: bearID,
	}
	mock.lockTrash.Lock()
	mock.calls.Trash = append(mock.calls.Trash, callInfo)
	mock.lockTrash.Unlock()
	return mock.TrashFunc(ctx, token, bearID)
}

// TrashCalls gets all the calls that were made to Trash.
// Check the length with:
//
//	len(mockedXCallback.TrashCalls())
func (mock *XCallbackMock) TrashCalls() []struct {
	Ctx    context.Context
	Token  string
	BearID string
} {
	var calls []struct {
		Ctx    context.Context
		Token  string
		BearID string
	}
	mock.lockTrash.RLock()
	calls = mock.calls.Trash
	mock.lockTrash.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *XCallbackMock) Update(ctx context.Context, token string, bearID string, body string) error {
	if mock.UpdateFunc == nil {
		panic("XCallbackMock.UpdateFunc: method is nil but XCallback.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Token  string
		BearID string
		Body   string
	}{
		Ctx:    ctx,
		Token:  token,
		BearID: bearID,
		Body:   body,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, token, bearID, body)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedXCallback.UpdateCalls())
func (mock *XCallbackMock) UpdateCalls() []struct {
	Ctx    context.Context
	Token  string
	BearID string
	Body   string
} {
	var calls []struct {
		Ctx    context.Context
		Token  string
		BearID string
		Body   string
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
